_CA_NEW() { IS_NEW=1 _CA_CLONE_OR_NEW $@; }
_CA_CLONE() { IS_NEW=0 _CA_CLONE_OR_NEW $@; }

_CA_CLONE_OR_NEW() {
	local BASE_DIR="$1"
	local REMOTE_TARGET="$2"
	local PROJECT_NAME="$3"
	
	[ ! $BASE_DIR ] && BASE_DIR=$(_CA__SELECT_BASE_DIR)
	[ ! $BASE_DIR ] && return 1

	[ ! $REMOTE_TARGET ] && REMOTE_TARGET=$(_CA__GET_REMOTE_TARGET)
	[ ! $REMOTE_TARGET ] && return 1

	[[ $REMOTE_TARGET =~ .git$ ]] || return 1

	[ ! $PROJECT_NAME ] && PROJECT_NAME=$(_CA__GET_PROJECT_NAME $REMOTE_TARGET)
	[ ! $PROJECT_NAME ] && return 1

	local PROJECT_PATH="$BASE_DIR/$PROJECT_NAME"

	[[ $IS_NEW -eq 0 ]] && _CA__GIT_CLONE $PROJECT_PATH $REMOTE_TARGET
	[[ $IS_NEW -eq 1 ]] && _CA__GIT_INIT $PROJECT_PATH $REMOTE_TARGET

	_CA_ACTIVATE "$(basename $BASE_DIR)/$PROJECT_NAME"
}
